name: Require PullRequest Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  require-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Verify that PullRequest has reviewed
        if: ${{ github.event.pull_request.base.ref == 'master' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_review') }}
        uses: actions/github-script@v6
        id: check_review
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            
            const pullRequestReviewed = reviews.find(review => 
              review.user.login === 'patrick-local[bot]' && review.state === 'APPROVED'
            );
            
            if (pullRequestReviewed) {
              echo "reviewed" >> $GITHUB_ENV
            }

      - name: Determine status
        if: env.STATUS_CHECK != 'reviewed'
        run: |
          echo "PullRequest has not yet reviewed this change."
          exit 1
