name: Require PullRequest Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  require-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Verify that PullRequest has reviewed
        if: ${{ github.event.pull_request.base.ref == 'master' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_review') }}
        uses: actions/github-script@v6
        id: check_review
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            
            const pullRequestApproval = reviews.find(review => 
              review.user.login === 'patrick-local[bot]' && review.state === 'APPROVED'
            );
            
            if (!pullRequestApproval) {
              return 'pending';
            } else {
              return 'reviewed';
            }

      - name: Determine status
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_review'
        run: |
          if [[ "${{ steps.check_branch.outputs.result }}" == "reviewed" ]]; then
            echo "reviewed" >> $GITHUB_ENV
          fi

      - name: Update GitHub Status Check
        uses: actions/github-script@v6
        with:
          script: |
            const status = process.env.STATUS_CHECK || 'pending';
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: status === 'reviewed' ? 'success' : 'pending',
              context: 'PullRequest Review Status',
              description: status === 'success' ? 'PullRequest has reviewed this change.' : 'Waiting for PullRequest to review this change.',
            });
