name: Require PullRequest Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  require-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PullRequest Review
        id: check_review
        run: |
          echo "Checking for PullRequest reviews..."
          reviews=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews")

          if echo "$reviews" | jq -e '.[] | select(.user.login == "patrick-local[bot]" and .state == "APPROVED")' > /dev/null; then
            echo "reviewed" >> $GITHUB_ENV
          fi

      - name: Determine Status
        if: env.STATUS_CHECK != 'reviewed'
        run: |
          echo "PullRequest has not yet reviewed this change."
          exit 1
