name: Enforce Bot Approval on Specific Base Branch

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  check-bot-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check if bot has approved
        if: github.event.pull_request.base.ref == 'master'github.event.pull_request.base.ref && (github.event_name == 'pull_request' || github.event_name == 'pull_request_review')
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            
            const botApproval = reviews.find(review => 
              review.user.login === 'patrick-local[bot]' && review.state === 'APPROVED'
            );
            
            if (!botApproval) {
              throw new Error('Bot has not approved this PR targeting the master branch.');
            }
