name: Enforce Bot Review

on: [
  pull_request: [
    types:
      - opened
      - synchronize
      - edited
  ],
  pull_request_review: [
    types:
      - submitted
  ],
]

jobs:
  check-bot-review:
    if: ${{ github.event.pull_request.base.ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if bot has reviewed
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            
            const botReview = reviews.find(review => review.user.login === 'patrick-local[bot]' && review.state === 'APPROVED');
            
            if (!botReview) {
              throw new Error('Bot has not reviewed this PR.');
            }
